Undo add greeting because error
4:32:01 PM: ./src/components/features/ctf-components/ctf-hero-banner/ctf-hero-banner.tsx:103:5
4:32:01 PM: Type error: Property "greeting" does not exist on type "HeroBannerFieldsFragment".
4:32:01 PM:   101 |     headline,
4:32:01 PM:   102 |     // Tutorial: uncomment the line below to make the Greeting field available to render
4:32:01 PM: > 103 |     greeting,
4:32:01 PM:       |     ^
4:32:01 PM:   104 |     bodyText,
4:32:01 PM:   105 |     ctaText,
4:32:01 PM:   106 |     targetPage,